#Portfolio settings
title: Landrik || Code &amp; Design by Landry Karege
email: landrik@gmail.com
description: Front-end developer // Free thinker // UX/UI Designer

#menu item list
menu:
- {index: 2, name: Profile, url: '#profile'}
- {index: 3, name: Portfolio, url: '#portfolio'}
- {index: 4, name: Contact, url: '#contact'}
- {index: 1, name: Home, url: '#intro'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.
seo:
  description: 'Landry Karege is a London based Freelance UX/UI Digital Designer and Front End Developer'
  rel-author: 'landrik'
  rel-publisher: 'landrik'

#-------------------------------

#Skill List

skills:
- {name: ADOBE Tools, value: '95'}
- {name: HTML5 & CSS, value: '98'}
- {name: JS & jQuery, value: '75'}
- {name: PHP & MySQL, value: '80'}


projects:
- {name: BBC Asset & Marketing, folder: 'proj-1'}
- {name: Oficial London Theatre, folder: 'proj-3'}
- {name: Marketing Print, folder: 'proj-6'}

#- {name: America As You Like It, folder: 'proj-2'}
#- {name: Gosh Pr, folder: 'proj-4'}
#- {name: Ronnie Wood, folder: 'proj-5'}


#Site default images and content
avatar: face.png

blurb: <p>Hi! my name is <b>Landry Karege</b>, I am a UI developer based in London, England. In over 6 years I have been in the industry, I have been lucky enough to work with some amazing folks from all background, together we have worked on many projects for a wide range of clients including the recent BBC and American Airlines.</p><p>This has taught me to look at design as not a solution to prettify a webpage, instead as a key answer to many businesses growth as well as perception.</p><p>My work mainly focuses on Interactive, Web- &amp; UI-Design, as well as development. So if you want to work or collaborate with me, do not hesitate to send me an <a href='#contact'>email</a>.</p>

#testimonials section
testimonials:
- {name: 'Theo BC', quote: 'Landry is a fantastic web designer and developer who brings creativity, knowledge and enthusiasm to every project he works on. Working under pressure on high profile client engagements, I could always rely on Landry to produce beautiful, cutting edge user interface and graphic work to tight deadlines. He is someone who has exactly the right attitude - never hesitant to pitch in and help other people, always dedicated to producing the very best work possible and ensuring milestones are met. Approachable, available and a huge player on any team, I cannot recommend Landry highly enough. I sincerely hope to work with him again in the future.'}
- {name: 'Ruth Peters', quote: 'I have worked with Landry at VYRE and then North Plains. At all times his standard of work has been extremely high and his ability to go the extra mile for clients and colleagues always highly valued'}
- {name: 'Alan Henning', quote: 'Landry has a great balance of commercial web knowledge. This enabled him to bring excellent web, editorial and development skills to his role at Iomart.'}
- {name: 'Deena Brown', quote: 'I have been fortunate to work with Landry on a number of different projects. Landry is an excellent designer who always ensures he thoroughly understands the task he is being asked to undertake before embarking on any project. His work is therefore always on brief as well as high quality and creative. Landry always maintains a professional and calm exterior even when he is up against tight deadlines. I enjoy working with him and am always delighted when he has time to help marketing!'}
- {name: 'Wes Hitch', quote: "Landry was 1 of the nicest staff members I've ever had to manage. As we as a team developed, Landry quickly came from needing guidance to providing the rest of the team with knowledge which would have been lacking without his input. It's been several years now since we've worked together, so I'd be very, very surprised if he's not a strong team lead at this point in his career. Pleasant, bright, and good at his job, with a lot of scope for further career development if his character and skills are recognised. I'd hire again!"}


#Contact
social:
- {icon: 'linkedin', link: 'http://linkedin.com'}
- {icon: 'github', link: 'http://github.com'}
- {icon: 'codepen', link: 'http://codepen.com'}
- {icon: 'twitter', link: 'http://twitter.com'}
